name: Postagem Vecel 

on:
  push:
    branches:
      - main

jobs:
  copy_files:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.email "tbg.barros@hotmail.com"
        git config --global user.name "tbgbarros"

    - name: Copy files to existing repository
      run: |
        cp -r PI_4SEM_2024/CODIFICAÇÃO/. HackersSchool
        cd HackersSchool

    - name: Commit changes
      run: |
        git add .
        git commit -m "Copy files from original repository"
    
    - name: Push changes
      run: |
        git push
